name: "Check plugin with multiple PHP versions"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Check there is no syntax errors in the project
  php-linter:
    name: Check plugin code compatibility with multiple PHP versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: PHP syntax checker 5.4
        uses: prestashop/github-action-php-lint/5.4@master
        with:
          working-directory: simple-jwt-login/

      - name: PHP syntax checker 5.5
        uses: prestashop/github-action-php-lint/5.5@master
        with:
          working-directory: simple-jwt-login/

      - name: PHP syntax checker 5.6
        uses: prestashop/github-action-php-lint/5.6@master
        with:
          working-directory: simple-jwt-login/

      - name: PHP syntax checker 7.1
        uses: prestashop/github-action-php-lint/7.1@master
        with:
          working-directory: simple-jwt-login/

      - name: PHP syntax checker 7.2
        uses: prestashop/github-action-php-lint/7.2@master
        with:
          working-directory: simple-jwt-login/

      - name: PHP syntax checker 7.3
        uses: prestashop/github-action-php-lint/7.3@master
        with:
          working-directory: simple-jwt-login/

      - name: PHP syntax checker 7.4
        uses: prestashop/github-action-php-lint/7.4@master
        with:
          working-directory: simple-jwt-login/

      - name: PHP syntax checker 8.0
        uses: prestashop/github-action-php-lint/8.0@master
        with:
          working-directory: simple-jwt-login/

      - name: PHP syntax checker 8.1
        uses: prestashop/github-action-php-lint/8.1@master
        with:
          working-directory: simple-jwt-login/

      - name: PHP syntax checker 8.2
        uses: prestashop/github-action-php-lint/8.2@master
        with:
          working-directory: simple-jwt-login/
